export const languages = [
  "Tiếng Anh",
  "Tiếng Việt",
  "Krio",
  "Tiếng Ả Rập",
  "Tiếng Afrikaans",
  "Tiếng Akan",
  "Tiếng Albania",
  "Tiếng Amharic",
  "Tiếng Armenia",
  "Tiếng Assam",
  "Tiếng Aymara",
  "Tiếng Azerbaijan",
  "Tiếng Ba Lan",
  "Tiếng Ba Tư",
  "Tiếng Bambara",
  "Tiếng Bangla",
  "Tiếng Basque",
  "Tiếng Belarus",
  "Tiếng Bhojpuri",
  "Tiếng Bosnia",
  "Tiếng Bồ Đào Nha",
  "Tiếng Bulgaria",
  "Tiếng Catalan",
  "Tiếng Cebuano",
  "Tiếng Corsica",
  "Tiếng Croatia",
  "Tiếng Divehi",
  "Tiếng Do Thái",
  "Tiếng Dogri",
  "Tiếng Đan Mạch",
  "Tiếng Đức",
  "Tiếng Estonia",
  "Tiếng Ewe",
  "Tiếng Filipino",
  "Tiếng Frisia",
  "Tiếng Gael Scotland",
  "Tiếng Galician",
  "Tiếng Ganda",
  "Tiếng Georgia",
  "Tiếng Goan Konkani",
  "Tiếng Guarani",
  "Tiếng Gujarati",
  "Tiếng Hà Lan",
  "Tiếng Haiti",
  "Tiếng Hàn",
  "Tiếng Hausa",
  "Tiếng Hawaii",
  "Tiếng Hindi",
  "Tiếng Hmong",
  "Tiếng Hungary",
  "Tiếng Hy Lạp",
  "Tiếng Iceland",
  "Tiếng Igbo",
  "Tiếng Iloko",
  "Tiếng Indonesia",
  "Tiếng Ireland",
  "Tiếng Italy",
  "Tiếng Java",
  "Tiếng Kannada",
  "Tiếng Kazakh",
  "Tiếng Khmer",
  "Tiếng Kinyarwanda",
  "Tiếng Kurd",
  "Tiếng Kurd Miền Trung",
  "Tiếng Kyrgyz",
  "Tiếng La-tinh",
  "Tiếng Lào",
  "Tiếng Latvia",
  "Tiếng Lingala",
  "Tiếng Litva",
  "Tiếng Lushai",
  "Tiếng Luxembourg",
  "Tiếng Mã Lai",
  "Tiếng Macedonia",
  "Tiếng Maithili",
  "Tiếng Malagasy",
  "Tiếng Malayalam",
  "Tiếng Malta",
  "Tiếng Manipuri (Chữ Meitei Mayek)",
  "Tiếng Māori",
  "Tiếng Marathi",
  "Tiếng Miến Điện",
  "Tiếng Mông Cổ",
  "Tiếng Na Uy",
  "Tiếng Nepal",
  "Tiếng Nga",
  "Tiếng Nhật",
  "Tiếng Nyanja",
  "Tiếng Odia",
  "Tiếng Oromo",
  "Tiếng Pashto",
  "Tiếng Phạn",
  "Tiếng Pháp",
  "Tiếng Phần Lan",
  "Tiếng Punjab",
  "Tiếng Quechua",
  "Tiếng Quốc Tế Ngữ",
  "Tiếng Romania",
  "Tiếng Samoa",
  "Tiếng Séc",
  "Tiếng Serbia",
  "Tiếng Shona",
  "Tiếng Sindhi",
  "Tiếng Sinhala",
  "Tiếng Slovak",
  "Tiếng Slovenia",
  "Tiếng Somali",
  "Tiếng Sotho Miền Bắc",
  "Tiếng Sotho Miền Nam",
  "Tiếng Sunda",
  "Tiếng Swahili",
  "Tiếng Tajik",
  "Tiếng Tamil",
  "Tiếng Tatar",
  "Tiếng Tây Ban Nha",
  "Tiếng Telugu",
  "Tiếng Thái",
  "Tiếng Thổ Nhĩ Kỳ",
  "Tiếng Thụy Điển",
  "Tiếng Tigrinya",
  "Tiếng Trung (Giản Thể)",
  "Tiếng Trung (Phồn thể)",
  "Tiếng Tsonga",
  "Tiếng Turkmen",
  "Tiếng Ukraina",
  "Tiếng Urdu",
  "Tiếng Uyghur",
  "Tiếng Uzbek",
  "Tiếng Wales",
  "Tiếng Xhosa",
  "Tiếng Yiddish",
  "Tiếng Yoruba",
  "Tiếng Zulu",
];
