# This is a basic workflow to help you get started with Actions

name: Deploy NextJS to Ubuntu Server

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ['main']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checking out latest code
              uses: actions/checkout@v3
            # NodeJS Setup
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: 18
            - run: npm i -g pnpm
            - run: pnpm install
            - run: pnpm build
            # Copy workspace into server
            - name: Deploy to Staging server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_SSH_KEY }}
                  source: '*'
                  target: '/var/www/capstone/client'

            - name: Restart the app
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  port: ${{ secrets.REMOTE_PORT }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_SSH_KEY }}
                  script: cd /var/www/capstone/client && sudo rm -rf .git .github .idea && sudo systemctl restart capstone-client